test:
  adapter: postgresql
  database: ground_zero_test
  host: localhost
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: ground_zero_development
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql